//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace World_Skills_X.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars_stats
    {
        public int Id_car { get; set; }
        public Nullable<int> Car_spawn_ticks { get; set; }
        public Nullable<int> Car_exit_ticks { get; set; }
    }
}
