//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace World_Skills_X.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traffic_light
    {
        public int Id_light { get; set; }
        public Nullable<int> Car_count_full_run { get; set; }
        public Nullable<int> Car_average_in_minute { get; set; }
        public Nullable<int> Count_color_switches { get; set; }
    }
}
